// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZco5B1nQbF5xjFTJNw_oEvDKvhixQjWk',
    appId: '1:978923954572:web:2de8ff5a3633cd5a0736a9',
    messagingSenderId: '978923954572',
    projectId: 'todo-with-chat',
    authDomain: 'todo-with-chat.firebaseapp.com',
    storageBucket: 'todo-with-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArzjwMtDgjCrGpGWsf1DZ4m9W2EwRzE4Q',
    appId: '1:978923954572:android:f6f015388ed546a20736a9',
    messagingSenderId: '978923954572',
    projectId: 'todo-with-chat',
    storageBucket: 'todo-with-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5YyJpRkATWFo-jmQF9SoodaQIWpTL-d8',
    appId: '1:978923954572:ios:7dcdd38ae772e3180736a9',
    messagingSenderId: '978923954572',
    projectId: 'todo-with-chat',
    storageBucket: 'todo-with-chat.appspot.com',
    iosBundleId: 'com.example.todoWithChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5YyJpRkATWFo-jmQF9SoodaQIWpTL-d8',
    appId: '1:978923954572:ios:7dcdd38ae772e3180736a9',
    messagingSenderId: '978923954572',
    projectId: 'todo-with-chat',
    storageBucket: 'todo-with-chat.appspot.com',
    iosBundleId: 'com.example.todoWithChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZco5B1nQbF5xjFTJNw_oEvDKvhixQjWk',
    appId: '1:978923954572:web:9f929ac1eb539b870736a9',
    messagingSenderId: '978923954572',
    projectId: 'todo-with-chat',
    authDomain: 'todo-with-chat.firebaseapp.com',
    storageBucket: 'todo-with-chat.appspot.com',
  );
}
